config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end
  
  resources :modifications, only: [:new, :create, :index, :destroy]
  get '/modifications' => 'modifications#index'

  resources :posts
  resources :contacts
  get '/posts' => 'posts#index'
  get '/about' => 'pages#about'
  get '/pulse' => 'pages#pulse'
  get '/collection' => 'pages#collection'
  get '/market' => 'pages#market'
  get '/affair' => 'pages#affair'
  get '/time' => 'pages#time'
  get '/past' => 'pages#past'
  get '/present' => 'pages#present'
  get '/future' => 'pages#future'
  get '/plans' => 'pages#plans'
  get '/home' => 'pages#home'
  root 'pages#landing'
  

end

app/models/modification.rb
class Modification < ActiveRecord::Base
    
    has_attached_file :image,
        styles: {
            thumb: ["64x64#", :jpg],
            original: ['500x500>', :jpg] },
            
        convert_options: { 
            thumb: "-quality 75 -strip",
            original: "-quality 85 -strip" }
        
    validates_attachment :image, presence: true,
        content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
        
end

app/controllers/modifications_controller.rb
class ModificationsController < ApplicationController
    
  def index
    @modifications = Modification.order('created_at')
    @modifications = Modification.paginate(page: params[:page])
  end

  def new
    @modifications = Modification.new
  end

  def create
    @modifications = Modification.new(modification_params)
    if @modifications.save
      flash[:success] = "Modification contributed!"
      redirect_to modifications_path
    else
      render 'new'
    end
  end
  
  def destroy
    @modifications = Modification.find(params[:id])
    @modifications.destroy
    flash[:danger] = "Contribution removed!"
    redirect_to modifications_path
  end

  private

  def modification_params
    params.require(:modification).permit(:image, :title)
  end
  
end

app/views/modifications/_filter.html.erb
<!--Modification Styles-->
<div class="row text-center">
       
    <!--Styles-->
    <%= render 'modifications/styles' %>
    
    <!--Uploader-->
    <div class="col-lg-4">
        <a><%= link_to "CONTRIBUTE", new_modification_path, class:'btn btn-info btn-lg btn-block' %></a>
    </div>
    
    <!--Random Content-->
    <div class="col-lg-4">
        <a><%= link_to "RANDOM", modifications_path, class:'btn btn-lg btn-block' %></a>
    </div>
</div>

<hr />

<div class="row text-center">
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"),  class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>TATTOOS</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>PIERCING</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>AUGMENTATION</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>COSMETIC</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>STRETCHING</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>LASER</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>EXO-SKELETON</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>BODY BUILDING</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>SCARIFICATION</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>AMPUTATION</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>SPLITTING</h4>
            </div>
        <% end %>
    </div>
    
    <div class="col-md-3">
        <%= link_to modifications_path do %>
            <%= image_tag ("tattoos.jpg"), class:'modification-style-img' %>
            <div class="modification-style-caption">
                <h4>OTHER</h4>
            </div>
        <% end %>
    </div>
</div>

app/views/modifications/_modification.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="media text-center">
      
      <div class="media-body">
        <h4 class="media-heading"><%= modification.title %></h4>
        <!--<%= link_to 'Remove', modification_path(modification), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>-->
      </div>
      
      <div class="media-center">
        <%= link_to image_tag(modification.image.url, class: 'media-object img-circle',  width:'250', height:'250' ), modification.image.url, target: '_blank' %>
        <!--<%= link_to image_tag(modification.image.url(:thumb), class: 'media-object img-rounded'), modification.image.url, target: '_blank' %>-->
      </div>
  
    </div>
  </div>
</div>

app/views/modifications/_styles.html.erb
<!--Styles Dropdown-->
<div class="col-lg-4">
    <div class="btn-group">
        
      <button type="button" class="btn btn-lg btn-block dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        STYLES <span class="caret"></span>
      </button>
      
      <ul class="dropdown-menu">
        <a href="#" class="list-group-item text-center">Tattoo</a>
        <a href="#" class="list-group-item text-center">Piercing</a>
        <a href="#" class="list-group-item text-center">Cosmetic</a>
        <a href="#" class="list-group-item text-center">Laser</a>
        <a href="#" class="list-group-item text-center">Augmentation</a>
        <a href="#" class="list-group-item text-center">Stretching</a>
        <a href="#" class="list-group-item text-center">Scarification</a>
        <a href="#" class="list-group-item text-center">Splitting</a>
        <a href="#" class="list-group-item text-center">Exoskeleton</a>
        <a href="#" class="list-group-item text-center">Amputation</a>
        <a href="#" class="list-group-item text-center">Bodybuilding</a>
      </ul>
      
    </div>
</div>

app/views/modifications/index.html.erb
<!--Title-->
<% provide(:title, 'Modifications') %>

<!--Header-->
<div class="jumbotron text-center">
    <h1>COLLECTION</h1>
    <h2>MODIFICATIONS</h2>
</div>

<!--Body-->
<!--Collection/Modifications-->
<div class="well">
    
    <!--Collection Navbar-->
    <%= render 'shared/collection_navbar' %>
    
    <hr />
 
    <!--Styles-->
    <%= render 'modifications/styles' %>
    
    <!--Uploader-->
    <div class="col-lg-4">
        <a><%= link_to "CONTRIBUTE", new_modification_path, class:'btn btn-info btn-lg btn-block' %></a>
    </div>
    
    <!--Random Content-->
    <div class="col-lg-4">
        <a><%= link_to "RANDOM", modifications_path, class:'btn btn-lg btn-block' %></a>
    </div>
    
    <hr />
    
    <!--Pagination-->
    <div class="row">
        <div class="text-center">
            <%= will_paginate %>
        </div>
    </div>
    
    <!--Modifications-->
    <%= render @modifications %>
    
    <!--Pagination-->
    <div class="row">
        <div class="text-center">
            <%= will_paginate %>
        </div>
    </div>
    
</div>

<!--Collection/Modifications Breadcrumb-->
<div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', home_path %></a></li>
      <li><a><%= link_to 'Collection', collection_path %></a></li>
      <li class="active">Modifications</li>
    </ol>
</div>

app/views/modifications/new.html.erb
<!--Title-->
<% provide(:title, 'Contribute') %>

<!--Header-->

<!--Body-->
<div class="container">
  <!--Display Contribution-->
  <div class="col-lg-6">
    <div class="panel panel-default">
      
      <div class="page-header text-center">
        <h2>MODIFICATION</h2>
        <h5>CONTRIBUTE</h5>
      </div>
      
      <%= form_for @modifications do |f| %>
      
      <%= render 'shared/errors', object: @modifications %>
    
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Name your modification...' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control'%>
      </div>
        
      <!--Modification Preview & Edit Tool Bar (Crop, Re-size, filters, auto-adjust)-->
      <div class="panel panel-default text-center">
        <h4>Editing Toolbelt</h4>
        <hr />
        <br />
        <h3>Display Modification</h3>
        <br />
        <h5>HERE</h5>
        <br />
      </div>
        
      <div class="form-group">
        <%= f.label :video %>
        <%= f.file_field :video, class: 'form-control'%>
      </div>
        
      </br />
      
    </div>
  </div>
  
  <!--Add Contribution Details-->
  <div class="col-lg-6">
    <div class="panel panel-default">
      
      <div class="page-header text-center">
        <h2>MODIFICATION</h2>
        <h5>DETAILS</h5>
      </div>
        
      <div class="form-group">
        <%= f.label :Center %>
        <input type="text" class="form-control" aria-label="..." placeholder="Where did you recieve your modification?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Technician %>
        <input type="text" class="form-control" aria-label="..." placeholder="Who performed your modification?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Designer %>
        <input type="text" class="form-control" aria-label="..." placeholder="Who designed your modification?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Styles %>
        <input type="text" class="form-control" aria-label="..." placeholder="What stlye is your modification?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Categories %>
        <input type="text" class="form-control" aria-label="..." placeholder="Which category does your modification fit into?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Sub_Categories %>
        <input type="text" class="form-control" aria-label="..." placeholder="Does your modification fit into a sub-category?"></input>
      </div>
      
      <div class="form-group">
        <%= f.label :Feedback %>
        <input type="text" class="form-control" aria-label="..." placeholder="Leave Feedback..."></input>
      </div>
      
    </div>
  </div>  
      
  <!--Submit Contribution-->
  <div class="col-lg-6 col-lg-offset-3">
    <div class="panel panel-default">
      
      <!--Social Share-->
      <div class="text-center">
        <h5>SOCIAL CONNECT</h5>
        <h6>SHARE YOUR MODIFICATION</h6>
        <div class="btn-lg btn-group btn-group-justified" role="group" aria-label="...">
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-instagram' %>
          </div>
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-snapchat' %>
          </div>
          
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-twitter' %>
          </div>
          
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-google' %>
          </div>
          
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-pinterest-p' %>
          </div>
          
          <div class="btn-group" role="group">
            <%= link_to "", "#", class:'btn btn-lg fa fa-facebook' %>
          </div>
        </div>
      </div>
      
      <hr />
      
      <!--Submit Action-->
      <div class="actions text-center">
        <%= f.submit "CONTRIBUTE", class:'btn btn-primary btn-lg btn-block' %>
      </div>
      
    </div>
  </div>
  
      <% end %>
      
    </div>  
  </div>
</div>