config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end
  
  resources :modifications, only: [:new, :create, :index, :destroy]
  get '/modifications' => 'modifications#index'

  resources :posts
  resources :contacts
  get '/posts' => 'posts#index'
  get '/about' => 'pages#about'
  get '/pulse' => 'pages#pulse'
  get '/collection' => 'pages#collection'
  get '/market' => 'pages#market'
  get '/affair' => 'pages#affair'
  get '/time' => 'pages#time'
  get '/past' => 'pages#past'
  get '/present' => 'pages#present'
  get '/future' => 'pages#future'
  get '/plans' => 'pages#plans'
  get '/home' => 'pages#home'
  root 'pages#landing'
  

end

app/views/pages/about.html.erb
<!--Title-->
<% provide(:title, 'About') %>


<h2>About US</h2>

app/views/pages/affair.html.erb
<!--Title-->
<% provide(:title, 'Affair') %>

<!--Jumbotron Heading-->
<div class="jumbotron">
    <h1 class="text-center">AFFAIR</h1>
</div>

<!--Affair Main-->
<div class="row">
        
    <div class="col-lg-4">
        <div class="panel panel-default">
            <h2 class="text-center">TOP AFFAIRs</h2>
            
            <hr />
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">3,216</span>
                <p class="list-group-item-text">Charleston, South Carolina, USA</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">2,961</span>
                    <p class="list-group-item-text">Miami, Florida, USA</p>
                    <h6>6/13/2016</h6>
                </a>
            </div>
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">2,341</span>
                <p class="list-group-item-text">New York City, New York, USD</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
        </div>
    </div>
    
    <div class="col-lg-4">
        <div class="panel panel-default">
            <h2 class="text-center">UPCOMING</h2>
            <hr />
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">327</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">1,323</span>
                    <p class="list-group-item-text">Charleston, South Carolina</p>
                    <h6>6/13/2016</h6>
                </a>
            </div>
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">487</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
        </div>
    </div>
    
    <div class="col-lg-4">
        <div class="panel panel-default">
            <h2 class="text-center">LOCAL</h2>
            
            <hr />
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">327</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">271</span>
                    <p class="list-group-item-text">Charleston, South Carolina</p>
                    <h6>6/13/2016</h6>
                </a>
            </div>
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">487</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
        </div>
    </div>

</div>

<div class="row">
    
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h4 class="text-center">MUTO AFFAIRS</h2>
            <hr />
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">312</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">271</span>
                    <p class="list-group-item-text">Charleston, South Carolina</p>
                    <h6>6/13/2016</h6>
                </a>
            </div>
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">241</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
        </div>
    </div>
    
    <div class="col-lg-6">
        <div class="panel panel-default">
            <h3 class="text-center">WORLD AFFAIRS MAP</h2>
        </div>
    </div>
    
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h4 class="text-center">NETWORK AFFAIRS</h2>
            <hr />
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">13</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
            
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">7</span>
                    <p class="list-group-item-text">Charleston, South Carolina</p>
                    <h6>6/13/2016</h6>
                </a>
            </div>
            
            <div class="list-group">
              <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">MUTO Affair</h4><span class="badge">27</span>
                <p class="list-group-item-text">Charleston, South Carolina</p>
                <h6>6/13/2016</h6>
              </a>
            </div>
        </div>
    </div>
    
</div>

<!--Affair Breadcrumb-->
<div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', root_path %></a></li>
      <li class="active">Affair</li>
    </ol>
</div>

app/views/pages/collection.html.erb
<!--Title-->
<% provide(:title, 'Collection') %>

<h1>COLLECTION</h1>

app/views/pages/future.html.erb
<!--Title-->
<% provide(:title, 'Future') %>

app/views/pages/home.html.erb
<div class="row">
    <% if user_signed_in? %>
    
        <%= render 'users/home' %>
        
    <% else %>
        <div class="row">
            <div class="col-lg-3">
                <div class="panel text-center">
                    <h4>JOINED ALREADY?</h4>
                    <br />
                    <%= link_to "ENTER", new_user_session_path, class:'btn btn-lg btn-info', method: :get %>
                </div>
            </div>
            <div class="col-lg-6 col-lg">
                <div class="panel text-center">
                    <h2>MUTO</h2>
                    <h3>Membership Plans</h3>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="panel text-center">
                    <h4>WHAT IS MUTO?</h4>
                    <br />
                    <%= link_to "ABOUT US", "#", class:'btn btn-lg btn-primary' %>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-3">
                <div class="well text-center">
                    
                    <!--Contributor-->
                    <h3>CONTRIBUTOR</h3><br />
                    
                    <%= image_tag ("contributor.jpg"), class: 'img-circle plan-image', width:'166', height:'166' %>
                   
                    <h5>BODY MODIFICATION</h5>
                    <h4>CLIENT</h4><hr />
                    
                    <button class="btn btn-info btn-block btn-lg" type="button" data-toggle="collapse" data-target="#collapseContributor" aria-expanded="false" aria-controls="collapseContributor">
                         CONTRIBUTOR
                    </button>
                    
                    <div class="collapse" id="collapseContributor"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @contributor_plan.id), class:'btn btn-info btn-block' %>
                            <h3>FREE</h3>
                            <hr>
                            <p>Discover Your Inner MUTO</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div><br />
                    
                    <button class="btn btn-warning btn-block" type="button" data-toggle="collapse" data-target="#collapseEliteContributor" aria-expanded="false" aria-controls="collapseEliteContributor">
                         ELITE CONTRIBUTOR
                    </button>
                    
                    <div class="collapse" id="collapseEliteContributor"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @elitecontributor_plan.id), class:'btn btn-warning btn-block' %>
                            <h3>$1<h5>(monthly)</h5></h3><hr />
                            <p>Discover Your Inner MUTO</p>
                            <p>Recieve Exclusive Offers!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <!--Technician-->
            <div class="col-lg-3">
                <div class="well text-center">
                    <h3>TECHNICIAN</h3><br />
                    
                    <%= image_tag ("technician.jpg"), class: 'img-circle plan-image', width:'166', height:'166' %>
                    
                    <h5>BODY MODIFICATION</h5>
                    <h4>PROFESSIONAL</h4><hr />
                    
                    <button class="btn btn-info btn-block btn-lg" type="button" data-toggle="collapse" data-target="#collapseTechnician" aria-expanded="false" aria-controls="collapseTechnician">
                         TECHNICIAN
                    </button>
                    
                    <div class="collapse" id="collapseTechnician"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @technician_plan.id), class:'btn btn-info btn-block' %>
                            <h3>FREE</h3>
                            <hr>
                            <p>Share your gift, modify the world!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div><br />
                    
                    <button class="btn btn-warning btn-block" type="button" data-toggle="collapse" data-target="#collapseEliteTechnician" aria-expanded="false" aria-controls="collapseInfo">
                         ELITE TECHNICIAN
                    </button>
                    
                    <div class="collapse" id="collapseEliteTechnician">
                        <br>
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @elitetechnician_plan.id), class:'btn btn-warning btn-block' %>
                            <h3>$6<h5>(monthly)</h5></h3>
                            <hr>
                            <p>Discover Your Inner MUTO</p>
                            <p>Recieve Exclusive Offers!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <!--Center-->
            <div class="col-lg-3">
                <div class="well text-center">
                    <h3>CENTER</h3><br />
                    
                    <%= image_tag ("center.jpg"), class: 'img-circle plan-image', width:'166', height:'166' %>
                    
                    <h5>BODY MODIFICATION</h5>
                    <h4>BUSINESS</h4><hr />
                    
                    <button class="btn btn-info btn-block btn-lg" type="button" data-toggle="collapse" data-target="#collapseCenter" aria-expanded="false" aria-controls="collapseCenter">
                         CENTER
                    </button>
                    
                    <div class="collapse" id="collapseCenter"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @center_plan.id), class:'btn btn-info btn-block' %>
                            <h3>FREE</h3>
                            <hr>
                            <p>Share your gift, modify the world!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div><br />
                    
                    <button class="btn btn-warning btn-block" type="button" data-toggle="collapse" data-target="#collapseEliteCenter" aria-expanded="false" aria-controls="collapseEliteCenter">
                         ELITE CENTER
                    </button>
                    
                    <div class="collapse" id="collapseEliteCenter"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @elitecenter_plan.id), class:'btn btn-warning btn-block' %>
                            <h3>$23<h5>(monthly)</h5></h3>
                            <hr>
                            <p>Supporting Technicians across the globe</p>
                            <p>Recieve Exclusive Offers!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div>
                </div>
            </div>
           
            <!--Affair-->
            <div class="col-lg-3">
                <div class="well text-center">
                    <h3>AFFAIR</h3><br />
                    
                    <%= image_tag ("affair.jpg"), class: 'plan-image', width:'166', height:'166' %>
                    
                    <h5>BODY MODIFICATION</h5>
                    <h4>EVENT</h4>
                    <hr>
                    <button class="btn btn-info btn-block btn-lg" type="button" data-toggle="collapse" data-target="#collapseAffair" aria-expanded="false" aria-controls="collapseAffair">
                         AFFAIR
                    </button>
                    
                    <div class="collapse" id="collapseAffair"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @affair_plan.id), class:'btn btn-info btn-block' %>
                            <h3>FREE</h3>
                            <hr>
                            <p>Share your gift, modify the world!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div><br />
                    
                    <button class="btn btn-warning btn-block" type="button" data-toggle="collapse" data-target="#collapseEliteAffair" aria-expanded="false" aria-controls="collapseEliteAffair">
                         ELITE AFFAIR
                    </button>
                    
                    <div class="collapse" id="collapseEliteAffair"><br />
                        <div class="panel">
                            <%= link_to "REGISTER", new_user_registration_path(plan: @eliteaffair_plan.id), class:'btn btn-warning btn-block' %>
                            <h3>$49<h5>(annual)</h5></h3>
                            <hr>
                            <p>Supporting Technicians across the globe</p>
                            <p>Recieve Exclusive Offers!</p>
                            <p>Contribute & Explore MUTO's Collection</p>
                            <p>Discover Local & Distant Modification Talent </p>
                            <p>Browse all your modification needs in the Market</p>
                            <p>Join others in attendance to modification Affairs across the globe</p>
                        </div>
                    </div>
                </div>
            </div>
    <% end %>
</div>

app/views/pages/landing.html.erb
<!--Title->
<% provide(:title, 'Body Modification') %>


<!--Body-->
<body class="landing">
    <div class="row">
        <div class="col-lg-3">
            <div class="landing-form">
                <div class="text-center">
                    <%= render 'shared/logo' %>
                        <h1>MUTO</h1>
                        <h6>BODY MODIFICATION</h6>
                    </div>
                </div>
                <hr />
                <div class="text-center">
                    <%= link_to "ENTER", new_user_session_path, class:'btn btn-lg btn-info btn-block', method: :get %>
                    <br />
                    <%= link_to "JOIN", home_path, class:'btn btn-md btn-success btn-block' %>
                    <br />
                    <br />
                    <%= link_to "About", "#", class:'btn btn-link' %> | 
                    <%= link_to "Help?", "#", class:'btn btn-link' %>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/pages/market.html.erb
<!--Title-->
<% provide(:title, 'Market') %>

<!--Header-->
<div class="jumbotron text-center">
    <h1>MARKET</h1>
</div>

<!--Community Breadcrumb-->
<div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', root_path %></a></li>
      <li class="active">Market</li>
    </ol>
</div>

app/views/pages/present.html.erb
<!--Title-->
<% provide(:title, 'Affair') %>

<!--Header-->

<!--Body-->

app/views/pages/pulse.html.erb
<!--Title-->
<% provide(:title, 'Pulse') %>

<!--Header-->
<div class="jumbotron text-center">
    <h1>PULSE</h1>
</div>

<!--Body-->
<div class="row text-center">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <h1>UPDATES</h1><hr />
            <ul class="media-list media-list-users list-group">
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                    <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Jacob Thornton</strong>
                    <small>@fat - San Francisco</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                    <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Dave Gamache</strong>
                    <small>@dhg - Palo Alto</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                   <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Mark Otto</strong>
                    <small>@mdo - San Francisco</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                   <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Mark Otto</strong>
                    <small>@mdo - San Francisco</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                   <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Mark Otto</strong>
                    <small>@mdo - San Francisco</small>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="media">
                  <a class="media-left" href="#">
                   <%= image_tag '', class:'media-object img-circle' %>
                  </a>
                  <div class="media-body">
                    <button class="btn btn-primary-outline btn-sm pull-right">
                      <span class="icon icon-add-user"></span> Follow
                    </button>
                    <strong>Mark Otto</strong>
                    <small>@mdo - San Francisco</small>
                  </div>
                </div>
              </li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h2><%= link_to 'POLL', '#', class:'h2' %></h2><hr />
            <h4>What is the best modification?</h4><br />
            <div class="input-group">
              <span class="input-group-addon">
                <input type="checkbox" aria-label="...">
              </span>
              <input type="text" class="form-control" aria-label="...">
            </div><br />
            <div class="input-group">
              <span class="input-group-addon">
                <input type="checkbox" aria-label="...">
              </span>
              <input type="text" class="form-control" aria-label="...">
            </div><br />
            <div class="input-group">
              <span class="input-group-addon">
                <input type="checkbox" aria-label="...">
              </span>
              <input type="text" class="form-control" aria-label="...">
            </div><br />
            <div class="input-group">
              <span class="input-group-addon">
                <input type="checkbox" aria-label="...">
              </span>
              <input type="text" class="form-control" aria-label="...">
            </div>
            <br />
            <p>Sponsored by <b>MUTO Charleston</b></p>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h2><%= link_to 'AFFAIRS', '#', class:'h2' %></h2><hr />
            <h5>Advertisement</h5>
            <hr />
            <h6>(location + popular)</h6>
            <h4>Recently Added</h4>
            <ul class="list-group">
                <li class="list-group-item">First Affair Post</li>
                <li class="list-group-item">Second Affair Post</li>
                <li class="list-group-item">Third Affair Post</li>
                <li class="list-group-item">Third Affair Post</li>
                <li class="list-group-item">Third Affair Post</li>
            </ul>
        </div>
    </div>
</div>
<div class="row text-center">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <h2><%= link_to 'CAREERS', posts_path, class:'h2' %></h2><hr />
            <h5>Advertisement</h5>
            <hr />
            <h6>(location + popular)</h6>
            <h4>Recently Added</h4>
            <ul class="list-group">
              <li class="list-group-item">First Career Post</li>
              <li class="list-group-item">Second Career Post</li>
              <li class="list-group-item">Third Career Post</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <h2><%= link_to 'MARKET', '#', class:'h2' %></h2><hr />
            <h5>Advertisement</h5>
            <hr />
            <h6>(location + popular)</h6>
            <h4>Recently Added</h4>
            <ul class="list-group">
              <li class="list-group-item">First Career Post</li>
              <li class="list-group-item">Second Career Post</li>
              <li class="list-group-item">Third Career Post</li>
            </ul>
        </div>
    </div>
     <div class="col-lg-4">
        <div class="panel panel-default">
            <h2><%= link_to 'TIME', '#', class:'h2' %></h2><hr />
            <h4>RECENT</h4>
            <h5>(recent + popular)</h5>
            <ul class="list-group">
              <li class="list-group-item">First Career Post</li>
              <li class="list-group-item">Second Career Post</li>
              <li class="list-group-item">Third Career Post</li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h2><%= link_to 'EDUCATION', '#', class:'h2' %></h2><hr />
            <h5>Advertisement</h5>
            <hr />
            <h6>(location + popular)</h6>
            <h4>Recently Added</h4>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <h2><%= link_to 'LAWS', '#', class:'h2' %></h2><hr />
        </div>
    </div>
</div>


<!--Community Breadcrumb-->
<div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', root_path %></a></li>
      <li class="active">Pulse</li>
    </ol>
</div>

app/views/pages/time.html.erb
<!--Title-->
<% provide(:title, 'Time') %>

<!--Header-->
<div class="jumbotron text-center">
    <h1>TIME</h1>
</div>

<!--Body-->
<div class="row">
    <div class="col-lg-4">
        <br />
        <div class="panel panel-default text-center">
            <%= link_to past_path do %>
                <h3>PAST</h3>
                <br />
                <i class="fa fa-undo"></i>
                <hr />
                <%= image_tag ("affair.jpg"), class: 'plan-image', width:'200', height:'200' %>
            <% end %>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default text-center">
            <%= link_to present_path do %>
                <h3>PRESENT</h3>
                <br />
                <i class="fa fa-circle-o"></i>
                <hr />
                <%= image_tag ("affair.jpg"), class: 'plan-image', width:'200', height:'200' %>
            <% end %>
        </div>
    </div>
    <div class="col-lg-4">
        <br />
        <div class="panel panel-default text-center">
            <%= link_to future_path do %>
                <h3>FUTURE</h3>
                <br />
                <i class="fa fa-repeat"></i>
                <hr />
                <%= image_tag ("affair.jpg"), class: 'plan-image', width:'200', height:'200' %>
            <% end %>
        </div>
    </div>
</div>

<!--Time Breadcrumb-->
<div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', root_path %></a></li>
      <li class="active">Time</li>
    </ol>
</div>