config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end
  
  resources :modifications, only: [:new, :create, :index, :destroy]
  get '/modifications' => 'modifications#index'

  resources :posts
  resources :contacts
  get '/posts' => 'posts#index'
  get '/about' => 'pages#about'
  get '/pulse' => 'pages#pulse'
  get '/collection' => 'pages#collection'
  get '/market' => 'pages#market'
  get '/affair' => 'pages#affair'
  get '/time' => 'pages#time'
  get '/past' => 'pages#past'
  get '/present' => 'pages#present'
  get '/future' => 'pages#future'
  get '/plans' => 'pages#plans'
  get '/home' => 'pages#home'
  root 'pages#landing'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:position, :location, :center, :wage, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :center %><br>
    <%= f.text_field :center, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :wage %><br>
    <%= f.number_field :wage, class:'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:'form-control' %>
  </div>
  <br>
  <div class="actions form-group text-center">
    <%= f.submit 'Add/Update Post', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="jumbotron text-center">
    <h1>Career Board</h1>
</div>
  
<div class="well">
    <div class="row text-center">
        <h2>Career Opportunity</h2>
        <h4>Edit Post</h4>
    </div>
    <hr>
    <%= render 'form' %>
    
    <hr>
    
    <div class="form-group text-center">
        <%= link_to 'Show', @post, class: 'btn btn-info' %> |
        <%= link_to 'Back', posts_path, class: 'btn btn-secondary' %>
    </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="jumbotron text-center">
    <h1>Career Board</h1>
  </div>

  <div class="well">
      <div class="row">
        <div class="col-lg-2">
          <div class="text-center">
            <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
          </div>
        </div>
        <!--Career Search-->
        <div class="col-lg-6 col-lg-offset-1">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search Careers...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
  </div>
    
  <hr>
  <!--Career Posts-->
  <div class="well">
    <br>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Position</th>
          <th>Date</th>
          <th>Location</th>
          <th>Center</th>
          <th>Wage</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.position %></td>
            <td><%= post.created_at.to_date %></td>
            <td><%= post.location %></td>
            <td><%= post.center %></td>
            <td><%= post.wage %></td>
            <td><%= post.description %></td>
            <td><%= link_to 'Show', post, class: 'btn btn-info' %></td>
            <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr>
    <nav class="text-center">
      <ul class="pagination">
        <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
  <!--Career Breadcrumb-->
  <div class="text-center">
    <ol class="breadcrumb">
      <li><a><%= link_to 'MUTO', root_path %></a></li>
      <li><a><%= link_to 'Pulse', pulse_path %></a></li>
      <li class="active">Careers</li>
    </ol>
  </div>
  
</div>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            
            <div class="page-header text-center">
                <h4>Career Opportunity</h4>
                <h1>New Post</h1>
            </div>
            
            <%= render 'form' %>
            
            <br>
            
            <div class="form-group text-center">
                <%= link_to 'Back', posts_path %>
            </div>

        </div>
    </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <div class= "jumbotron text-center">
    <h1>Career Board</h1>
  </div>    
  
  <div class="well">
    
    <div class="row">
      <div class="text text-center">
        <h2>Career Opportunity</h2>
      </div>
    </div>
    
      <hr>
    
    <div class='row'>
      <div class="col-sm-4 col-sm-offset-1">
        <p>
          <strong>Position:</strong>
          <%= @post.position %>
        </p>
      </div>
      <div class="col-sm-4 col-sm-offset-1">
        <p>
          <strong>Date:</strong>
          <%= @post.created_at.to_date %>
        </p>
      </div>
      <div class="col-sm-4 col-sm-offset-1">
        <p>
          <strong>Location:</strong>
          <%= @post.location %>
        </p>
      </div>
      <div class="col-sm-4 col-sm-offset-1">    
        <p>
          <strong>Center:</strong>
          <%= @post.center %>
        </p>
      </div>
      <div class="col-sm-4 col-sm-offset-1">    
        <p>
          <strong>Wage:</strong>
          <%= @post.wage %>
        </p>
      </div>
      <div class="col-sm-4 col-sm-offset-1">    
        <p>
          <strong>Description:</strong>
          <%= @post.description %>
        </p>
      </div>
    </div>
    
    <br>
    
    <div class="form-group text-center">
      <%= link_to 'Edit', edit_post_path(@post), class:'btn btn-warning' %> |
      <%= link_to 'Back', posts_path, class: 'btn btn-secondary' %>
    </div>
  </div>