config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
  end
  
  resources :modifications, only: [:new, :create, :index, :destroy]
  get '/modifications' => 'modifications#index'

  resources :posts
  resources :contacts
  get '/posts' => 'posts#index'
  get '/about' => 'pages#about'
  get '/pulse' => 'pages#pulse'
  get '/collection' => 'pages#collection'
  get '/market' => 'pages#market'
  get '/affair' => 'pages#affair'
  get '/time' => 'pages#time'
  get '/past' => 'pages#past'
  get '/present' => 'pages#present'
  get '/future' => 'pages#future'
  get '/plans' => 'pages#plans'
  get '/home' => 'pages#home'
  root 'pages#landing'
  

end

app/views/layouts/_footer.html.erb
<!--Footer-->
<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h5>© 2013-2016 MUTO</h5>
  </div>
    <div class="panel-body text-center">
      <a><%= link_to "About", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Help", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Contact", new_contact_path, class:'btn btn-link' %></a>
      <a><%= link_to "Advertise", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Terms", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Privacy", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Cookies", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Info", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Brand", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Forum", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Status", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Apps", '#', class:'btn btn-link' %></a>
      <a><%= link_to "Jobs", '#', class:'btn btn-link' %></a>
    </div>
</div>

app/views/layouts/_header.html.erb
<!--Header-->
<header>
  <nav class="navbar navbar-default navbar-static-top app-navbar" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle navbar-action" data-toggle="collapse" data-target="#main-navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="fa fa-navicon"></span>
        </button>
      </div>
      
      <!--Site Navigation-->
      <div class="collapse navbar-collapse text-center" id="main-navbar-collapse">
        <div class="nav navbar-nav navbar-left">
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag("navbar-logo-v1.png") %>
            </a>
            <ul class="dropdown-menu site-nav">
              <li><%= link_to "", pulse_path, class:'btn fa fa-heartbeat' %></li>
              <li><%= link_to "", users_path, class:'btn fa fa-eye' %></li>
              <li><%= link_to "", market_path, class:'btn fa fa-shopping-basket' %></li>
              <li><%= link_to "", affair_path, class:'btn fa fa-globe'  %></li>
              <li><%= link_to "", time_path, class:'btn fa fa-hourglass-start' %></li>
            </ul>
          </li>
        </div>
      
      <!--User Navigation-->
      <div class="collapse navbar-collapse text-center" id="main-navbar-collapse">
        <div class="nav navbar-nav navbar-right">
          <li role="presentation" class="dropdown">
            <% if user_signed_in? %>
              <% if current_user.profile %>
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <%= image_tag current_user.profile.avatar.url, class:'img-circle navbar-avatar' %>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "", home_path, class:'btn fa fa-home' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Profile"><%= link_to "", user_path(current_user), class:'text-center fa fa-male' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Modify Profile"><%= link_to "", edit_user_profile_path(current_user), class:'text-center fa fa-edit' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Notifications"><%= link_to "", "#", class:'text-center fa fa-bell' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Network"><%= link_to "", "#", class:'text-center fa fa-users' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Cart"><%= link_to "", "#" , class:'text-center fa fa-shopping-cart' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Settings"><%= link_to "", edit_user_registration_path, class:'text-center fa fa-cog' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Exit"><%= link_to "", destroy_user_session_path, class:'text-center fa fa-toggle-on', method: :delete %></li>
                </ul>
              <% else %>
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-bars" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu">
                  <li data-toggle="tooltip" data-placement="left" title="Exit"><%= link_to "", destroy_user_session_path, class:'text-center fa fa-toggle-on', method: :delete %></li>
                  <li data-toggle="tooltip" data-placement="left" title="CREATE PROFILE"><%= link_to "", new_user_profile_path(current_user), class:'text-center btn-warning fa fa-child' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Notifications"><%= link_to "", "#", class:'text-center fa fa-bell' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Network"><%= link_to "", "#", class:'text-center fa fa-users' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Cart"><%= link_to "", "#" , class:'text-center fa fa-shopping-cart' %></li>
                  <li data-toggle="tooltip" data-placement="left" title="Settings"><%= link_to "", edit_user_registration_path, class:'text-center fa fa-cog' %></li>
                </ul>
              <% end %>
            <% else %>
              
            <% end %>
          </li>
        </div>
      
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="MUTO Body Modification">
  <meta name="keywords" content="MUTO Body Modification">
  <meta name="author" content="Nathaniel Rand">
  
  <!--Title-->
  <title><%= full_title(yield(:title)) %></title>
  
  <!--Google Fonts-->
  <link href="https://fonts.googleapis.com/css?family=Quicksand|Raleway:600|Exo:500" rel="stylesheet">
  
  <!--CSS/JavaScript-->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>

<body>
  
<!--Navbar-->
<% if current_page?(root_path) %>
  <% else %>
    <%= render 'layouts/header' %>
<% end %>

<!--Alerts-->
<div class="container">
  <%  flash.each do |key,value| %>
    <%= content_tag :div, value, class:"alert alert-#{key} text-center"%>
  <% end %>
  <%= yield %>
</div>

<!--Footer-->
<% if current_page?(root_path) %>
  <% else %>
    <%= render 'layouts/footer' %>
<% end %>

<!--Javascript-->
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</body>
</html>